module.exports = {
    apps: [
        {
            name: 'antigravity-web',
            script: 'main.js',
            cwd: '/home/tiemuer/antigravity-web',
            env: {
                PORT: 3210,
                NODE_ENV: 'production',
            },
            watch: ['main.js', 'lib/', 'server.js'],
            ignore_watch: ['frontend', 'node_modules', 'logs', 'public', 'docs', 'tests', 'tools', '.git'],
            watch_delay: 1000,
            max_memory_restart: '300M',
            error_file: './logs/pm2-error.log',
            out_file: './logs/pm2-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'vite-dev',
            script: 'npx',
            args: 'vite --host 0.0.0.0 --port 5173',
            cwd: '/home/tiemuer/antigravity-web/frontend',
            watch: false,
            error_file: './logs/vite-error.log',
            out_file: './logs/vite-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'cloudflared',
            script: 'cloudflared',
            args: 'tunnel run antigravity-web',
            interpreter: 'none',
            cwd: '/home/tiemuer/antigravity-web',
            watch: false,
            error_file: './logs/cloudflared-error.log',
            out_file: './logs/cloudflared-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'ls-daemon',
            script: './scripts/ls-daemon.sh',
            args: 'start',
            interpreter: '/bin/bash',
            cwd: '/home/tiemuer/antigravity-web',
            env: {
                LS_PORT: 42100,
                LS_CSRF_TOKEN: 'pm2-ls-daemon-csrf-token-fixed',
            },
            watch: false,
            kill_timeout: 5000,
            // LS 是长驻进程，不需要自动重启（除非 crash）
            autorestart: true,
            max_restarts: 3,
            restart_delay: 5000,
            error_file: './logs/ls-daemon-error.log',
            out_file: './logs/ls-daemon-out.log',
            merge_logs: true,
            time: true,
        },
    ],
};
