module.exports = {
    apps: [
        {
            name: 'antigravity-web',
            script: 'main.js',
            cwd: '/home/tiemuer/antigravity-web',
            env: {
                PORT: 3210,
                NODE_ENV: 'production',
            },
            watch: ['main.js', 'lib/', 'server.js'],
            ignore_watch: ['frontend', 'node_modules', 'logs', 'public', 'docs', 'tests', 'tools', '.git'],
            watch_delay: 1000,
            max_memory_restart: '300M',
            error_file: './logs/pm2-error.log',
            out_file: './logs/pm2-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'vite-dev',
            script: 'npx',
            args: 'vite --host 0.0.0.0 --port 5173',
            cwd: '/home/tiemuer/antigravity-web/frontend',
            watch: false,
            error_file: './logs/vite-error.log',
            out_file: './logs/vite-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'cloudflared',
            script: 'cloudflared',
            args: 'tunnel run antigravity-web',
            interpreter: 'none',
            cwd: '/home/tiemuer/antigravity-web',
            watch: false,
            error_file: './logs/cloudflared-error.log',
            out_file: './logs/cloudflared-out.log',
            merge_logs: true,
            time: true,
        },
    ],
};
