// Proto file: exa/chat_pb/chat.proto
// Package: exa.chat_pb
syntax = "proto3";
package exa.chat_pb;

enum ChatFeedbackType {
  FEEDBACK_TYPE_UNSPECIFIED = 0;
  FEEDBACK_TYPE_ACCEPT = 1;
  FEEDBACK_TYPE_REJECT = 2;
  FEEDBACK_TYPE_COPIED = 3;
  FEEDBACK_TYPE_ACCEPT_DIFF = 4;
  FEEDBACK_TYPE_REJECT_DIFF = 5;
  FEEDBACK_TYPE_APPLY_DIFF = 6;
  FEEDBACK_TYPE_INSERT_AT_CURSOR = 7;
}

enum ChatIntentType {
  CHAT_INTENT_UNSPECIFIED = 0;
  CHAT_INTENT_GENERIC = 1;
  CHAT_INTENT_CODE_BLOCK_REFACTOR = 6;
  CHAT_INTENT_GENERATE_CODE = 9;
  CHAT_INTENT_FAST_APPLY = 12;
}

enum CacheControlType {
  CACHE_CONTROL_TYPE_UNSPECIFIED = 0;
  CACHE_CONTROL_TYPE_EPHEMERAL = 1;
}

message CodeBlockInfo {
  string raw_source = 1;
  int32 start_line = 2;
  int32 start_col = 3;
  int32 end_line = 4;
  int32 end_col = 5;
}

message ChatMetrics {
  uint64 response_stream_latency_ms = 1;
  uint64 refresh_context_latency_ms = 2;
  uint64 should_get_local_context_for_chat_latency_ms = 3;
  bool should_get_local_context_for_chat = 4;
  uint64 compute_change_events_latency_ms = 5;
  uint64 context_to_chat_prompt_latency_ms = 6;
  int32 num_prompt_tokens = 7;
  int32 num_system_prompt_tokens = 8;
  uint64 num_input_tokens = 16;
  google.protobuf.Timestamp start_timestamp = 9;
  google.protobuf.Timestamp end_timestamp = 10;
  string active_document_absolute_path = 11;
  exa.codeium_common_pb.CodeContextItem last_active_code_context_item = 12;
  uint64 num_indexed_files = 13;
  uint64 num_indexed_code_context_items = 14;
  exa.codeium_common_pb.Model model = 15;
}

message IntentGeneric {
  string text = 1;
  repeated exa.codeium_common_pb.TextOrScopeItem items = 2;
}

message IntentCodeBlockRefactor {
  exa.chat_pb.CodeBlockInfo code_block_info = 1;
  exa.codeium_common_pb.Language language = 2;
  string file_path_migrate_me_to_uri = 3;
  string uri = 5;
  string refactor_description = 4;
}

message IntentGenerateCode {
  string instruction = 1;
  exa.codeium_common_pb.Language language = 2;
  string file_path_migrate_me_to_uri = 3;
  string uri = 5;
  int32 line_number = 4;
}

message IntentFastApply {
  string diff_outline = 1;
  exa.codeium_common_pb.Language language = 2;
  exa.chat_pb.CodeBlockInfo old_code = 3;
}

message ChatMessageIntent {
  uint32 num_tokens = 12;
  oneof intent {
    exa.chat_pb.IntentGeneric generic = 1;
    exa.chat_pb.IntentCodeBlockRefactor code_block_refactor = 6;
    exa.chat_pb.IntentGenerateCode generate_code = 9;
    exa.chat_pb.IntentFastApply fast_apply = 13;
  }
}

message ChatMessageActionSearch {
}

message ChatMessageActionEdit {
  string file_path_migrate_me_to_uri = 1;
  string uri = 6;
  exa.diff_action_pb.DiffBlock diff = 2;
  exa.codeium_common_pb.Language language = 3;
  string text_pre = 4;
  string text_post = 5;
}

message ChatMessageActionGeneric {
  string text = 1;
  string display_text = 2;
}

message ChatMessageStatusContextRelevancy {
  bool is_loading = 1;
  bool is_relevant = 2;
  repeated string query_suggestions = 3;
}

message ChatMessageStatus {
  oneof status {
    exa.chat_pb.ChatMessageStatusContextRelevancy context_relevancy = 1;
  }
}

message ChatMessageError {
  string text = 1;
}

message ChatMessageAction {
  uint32 num_tokens = 2;
  repeated exa.codeium_common_pb.CodeContextItem context_items = 4;
  exa.chat_pb.ChatIntentType latest_intent = 6;
  exa.chat_pb.ChatMetrics generation_stats = 7;
  repeated exa.codeium_common_pb.KnowledgeBaseItemWithMetadata knowledge_base_items = 8;
  oneof action {
    exa.chat_pb.ChatMessageActionGeneric generic = 1;
    exa.chat_pb.ChatMessageActionEdit edit = 3;
    exa.chat_pb.ChatMessageActionSearch search = 5;
  }
}

message ChatMessage {
  string message_id = 1;
  exa.codeium_common_pb.ChatMessageSource source = 2;
  google.protobuf.Timestamp timestamp = 3;
  string conversation_id = 4;
  bool in_progress = 9;
  exa.chat_pb.GetChatMessageRequest request = 10;
  bool redact = 11;
  oneof content {
    exa.chat_pb.ChatMessageIntent intent = 5;
    exa.chat_pb.ChatMessageAction action = 6;
    exa.chat_pb.ChatMessageError error = 7;
    exa.chat_pb.ChatMessageStatus status = 8;
  }
}

message Conversation {
  repeated exa.chat_pb.ChatMessage messages = 1;
}

message ChatMessagePrompt {
  string message_id = 1;
  exa.codeium_common_pb.ChatMessageSource source = 2;
  string prompt = 3;
  uint32 num_tokens = 4;
  bool safe_for_code_telemetry = 5;
  repeated exa.codeium_common_pb.ChatToolCall tool_calls = 6;
  string tool_call_id = 7;
  exa.chat_pb.PromptCacheOptions prompt_cache_options = 8;
  bool tool_result_is_error = 9;
  repeated exa.codeium_common_pb.ImageData images = 10;
  repeated exa.codeium_common_pb.Media media = 19;
  string thinking = 11;
  string raw_thinking = 17;
  string signature = 12;
  bytes thinking_signature = 20;
  bool thinking_redacted = 13;
  repeated exa.codeium_common_pb.PromptAnnotationRange prompt_annotation_ranges = 14;
  int32 step_idx = 18;
  string provider_assigned_message_id = 21;
}

message ChatMessagePrompts {
  repeated exa.chat_pb.ChatMessagePrompt prompts = 1;
}

message PromptCacheOptions {
  exa.chat_pb.CacheControlType type = 1;
}

message ChatToolDefinition {
  string name = 1;
  string description = 2;
  string json_schema_string = 3;
  bool strict = 4;
  repeated string attribution_field_names = 5;
  string server_name = 6;
}

message ChatToolChoice {
  oneof choice {
    string option_name = 1;
    string tool_name = 2;
  }
}

message ChatMentionsSearchRequest {
  string query = 1;
  repeated exa.codeium_common_pb.CodeContextType allowed_types = 2;
  bool include_repo_info = 3;
}

message ChatMentionsSearchResponse {
  repeated exa.codeium_common_pb.CodeContextItem cci_items = 1;
  repeated exa.codeium_common_pb.GitRepoInfo repo_infos = 2;
}

message GetChatMessageRequest {
  exa.codeium_common_pb.Metadata metadata = 1;
  repeated exa.chat_pb.ChatMessage chat_messages = 3;
  exa.codeium_common_pb.Document active_document = 5;
  repeated string open_document_uris = 12;
  repeated string workspace_uris = 13;
  string active_selection = 11;
  exa.codeium_common_pb.ContextInclusionType context_inclusion_type = 8;
  exa.codeium_common_pb.Model chat_model = 9;
  string system_prompt_override = 10;
  string chat_model_name = 14;
  exa.chat_pb.GetChatMessageRequest.EnterpriseExternalModelConfig enterprise_chat_model_config = 15;
  exa.codeium_common_pb.ExperimentConfig experiment_config = 4;
  repeated string open_document_paths_migrate_me_to_uris = 6;
  repeated string workspace_paths_migrate_me_to_uris = 7;
  message EnterpriseExternalModelConfig {
    int32 max_output_tokens = 2;
    int32 max_input_tokens = 3;
  }
}

message ChatExperimentStatus {
  exa.codeium_common_pb.ExperimentKey experiment_key = 1;
  bool enabled = 2;
}

message FormattedChatMessage {
  exa.codeium_common_pb.ChatMessageSource role = 1;
  string header = 2;
  string content = 3;
  string footer = 4;
}

message IndexMap {
  repeated exa.chat_pb.IndexMap.IndexMapEntry index_map = 1;
  message IndexList {
    repeated int32 indices = 1;
  }
  message IndexMapEntry {
    int32 key = 1;
    exa.chat_pb.IndexMap.IndexList value = 2;
  }
}

message ChatMessageRollout {
  string system_prompt = 1;
  repeated exa.chat_pb.ChatToolDefinition tools = 2;
  exa.chat_pb.ChatToolChoice tool_choice = 3;
  repeated exa.chat_pb.ChatMessagePrompt input_chat_messages = 4;
  repeated exa.chat_pb.ChatMessagePrompt output_chat_messages = 5;
  exa.chat_pb.IndexMap trajectory_to_chat_message_index_map = 6;
}

message XboxInferenceToolRequest {
  string model_name = 3;
  string model_enum = 4;
  exa.chat_pb.Example gemini_example = 2;
}

message Example {
  repeated exa.chat_pb.Message messages = 1;
}

message Message {
  string role = 1;
  repeated exa.chat_pb.Chunk chunks = 2;
}

message Chunk {
  enum Trainable {
    UNKNOWN_TRAINABLE = 0;
    FORMATTER_DEFINED = 1;
    ALWAYS = 2;
    NEVER = 3;
  }
  exa.chat_pb.Chunk.Trainable trainable = 10;
  oneof value {
    string text = 3;
    exa.chat_pb.Image image = 4;
  }
}

message Image {
  exa.chat_pb.FileData value = 5;
  int32 height_px = 3;
  int32 width_px = 4;
}

message FileData {
  bytes content = 3;
  string mime_type = 2;
}

message RpcRequest {
  string id = 3;
  oneof request {
    exa.chat_pb.RunToolRequest run_tool_request = 1;
  }
}

message RpcResponse {
  string request_id = 2;
  oneof response {
    exa.chat_pb.RunToolResponse run_tool_response = 1;
  }
}

message RunToolRequest {
  string name = 1;
  string operation_id = 2;
  string parameters = 3;
}

message RunToolResponse {
  string response = 1;
  exa.chat_pb.RunToolResponse.Status status = 2;
  message Status {
    int32 code = 1;
    string status_message = 2;
  }
}
