// Proto file: exa/cascade_plugins_pb/cascade_plugins.proto
// Package: exa.cascade_plugins_pb
syntax = "proto3";
package exa.cascade_plugins_pb;

message CascadePluginTemplate {
  string title = 1;
  string id = 2;
  string link = 3;
  string description = 4;
  repeated exa.cascade_plugins_pb.CascadePluginTemplate.CommandsEntry commands = 5;
  int64 installation_count = 6;
  string trust_level = 7;
  string readme = 8;
  oneof configuration {
    exa.cascade_plugins_pb.CascadePluginLocalConfig local = 9;
    exa.cascade_plugins_pb.CascadePluginRemoteConfig remote = 10;
  }
  message CommandsEntry {
    string key = 1;
    exa.cascade_plugins_pb.CascadePluginCommand value = 2;
  }
}

message CascadePluginLocalConfig {
  repeated exa.cascade_plugins_pb.CascadePluginLocalConfig.CommandsEntry commands = 5;
  message CommandsEntry {
    string key = 1;
    exa.cascade_plugins_pb.CascadePluginCommand value = 2;
  }
}

message CascadePluginCommand {
  exa.cascade_plugins_pb.CascadePluginCommandTemplate template = 1;
  repeated exa.cascade_plugins_pb.CascadePluginCommandVariable variables = 2;
}

message CascadePluginCommandTemplate {
  string command = 1;
  repeated string args = 2;
  repeated exa.cascade_plugins_pb.CascadePluginCommandTemplate.EnvEntry env = 3;
  message EnvEntry {
    string key = 1;
    string value = 2;
  }
}

message CascadePluginCommandVariable {
  string name = 1;
  string title = 2;
  string description = 3;
  string link = 4;
}

message CascadePluginRemoteConfig {
  exa.cascade_plugins_pb.CascadePluginRemoteConfigTemplate template = 1;
}

message CascadePluginRemoteConfigTemplate {
  string server_url = 1;
  repeated exa.cascade_plugins_pb.CascadePluginRemoteConfigTemplate.HeadersEntry headers = 2;
  message HeadersEntry {
    string key = 1;
    string value = 2;
  }
}

message GetAvailableCascadePluginsRequest {
  exa.codeium_common_pb.Metadata metadata = 1;
  string os = 2;
}

message GetAvailableCascadePluginsResponse {
  repeated exa.cascade_plugins_pb.CascadePluginTemplate plugins = 1;
}

message InstallCascadePluginRequest {
  exa.codeium_common_pb.Metadata metadata = 1;
  string plugin_id = 2;
}

message InstallCascadePluginResponse {
  int64 installation_count = 1;
}

message GetCascadePluginByIdRequest {
  exa.codeium_common_pb.Metadata metadata = 1;
  string os = 2;
  string plugin_id = 3;
}

message GetCascadePluginByIdResponse {
  exa.cascade_plugins_pb.CascadePluginTemplate plugin = 1;
}

service CascadePluginsService {
  rpc GetAvailableCascadePlugins (stream exa.cascade_plugins_pb.GetAvailableCascadePluginsRequest) returns (exa.cascade_plugins_pb.GetAvailableCascadePluginsResponse);
  rpc InstallCascadePlugin (stream exa.cascade_plugins_pb.InstallCascadePluginRequest) returns (exa.cascade_plugins_pb.InstallCascadePluginResponse);
  rpc GetCascadePluginById (stream exa.cascade_plugins_pb.GetCascadePluginByIdRequest) returns (exa.cascade_plugins_pb.GetCascadePluginByIdResponse);
}
