// Proto file: exa/chat_client_server_pb/chat_client_server.proto
// Package: exa.chat_client_server_pb
syntax = "proto3";
package exa.chat_client_server_pb;

enum ChatClientRequestStreamClientType {
  CHAT_CLIENT_REQUEST_STREAM_CLIENT_TYPE_UNSPECIFIED = 0;
  CHAT_CLIENT_REQUEST_STREAM_CLIENT_TYPE_IDE = 1;
  CHAT_CLIENT_REQUEST_STREAM_CLIENT_TYPE_BROWSER = 2;
}

message StartChatClientRequestStreamRequest {
  exa.chat_client_server_pb.ChatClientRequestStreamClientType client_type = 1;
}

message ChatClientRequest {
  oneof request {
    exa.chat_client_server_pb.AddCascadeInputRequest add_cascade_input = 1;
    exa.chat_client_server_pb.SendActionToChatPanelRequest send_action_to_chat_panel = 2;
    exa.chat_client_server_pb.InitialAckRequest initial_ack = 3;
    exa.chat_client_server_pb.RefreshCustomizationRequest refresh_customization = 4;
  }
}

message AddCascadeInputRequest {
  repeated exa.codeium_common_pb.TextOrScopeItem items = 1;
  repeated exa.codeium_common_pb.ImageData images = 2;
  repeated exa.codeium_common_pb.Media media = 3;
}

message SendActionToChatPanelRequest {
  string action_type = 1;
  repeated bytes payload = 2;
}

message InitialAckRequest {
}

message RefreshCustomizationRequest {
  exa.codeium_common_pb.RefreshCustomizationType config_type = 1;
}

service ChatClientServerService {
  rpc StartChatClientRequestStream (exa.chat_client_server_pb.StartChatClientRequestStreamRequest) returns (exa.chat_client_server_pb.ChatClientRequest);
}
